Sat Jul 23 20:51:05 2022
Windows-10-10.0.22000
Ren'Py 7.4.10.2178
 

Bootstrap to the start of init.init took 0.06s
Early init took 0.00s
Loader init took 0.01s
Loading error handling took 0.01s
Loading script took 0.41s
Loading save slot metadata. took 0.03s
Loading persistent took 0.00s
Importing _renpysteam: ImportError('No module named _renpysteam',)
Running init code took 0.04s
Loading analysis data took 0.01s
Analyze and compile ATL took 0.00s
Index archives took 0.00s
Backing up script files to 'C:\\Users\\lenovo\\AppData\\Roaming/RenPy/backups\\Healthy and Safety':
Dump and make backups. took 0.05s
Cleaning cache took 0.00s
Making clean stores took 0.00s
Initial gc. took 0.02s
DPI scale factor: 1.250000
nvdrs: Loaded, about to disable thread optimizations.
nvdrs: Disabled thread optimizations.
Creating interface object took 0.18s
Cleaning stores took 0.00s
Init translation took 0.03s
Build styles took 0.00s
Load screen analysis took 0.00s
Analyze screens took 0.01s
Save screen analysis took 0.03s
Prepare screens took 0.04s
Save pyanalysis. took 0.03s
Save bytecode. took 0.02s
Running _start took 0.00s
Performance test:
Interface start took 0.08s

Initializing gl2 renderer:
primary display bounds: (0, 0, 1920, 1080)
swap interval: 1 frames
Windowed mode.
Vendor: 'NVIDIA Corporation'
Renderer: 'NVIDIA GeForce RTX 3050 Ti Laptop GPU/PCIe/SSE2'
Version: '4.6.0 NVIDIA 516.59'
Display Info: None
Screen sizes: virtual=(1920, 1080) physical=(1733, 975) drawable=(1733, 975)
Maximum texture size: 4096x4096

Full traceback:
  File "game/chapter2.rpy", line 520, in script
    Kevin "So you're back, how was the training today?"
  File "renpy/ast.py", line 721, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "renpy/exports.py", line 1417, in say
    who(what, *args, **kwargs)
  File "renpy/character.py", line 1249, in __call__
    self.do_display(who, what, cb_args=self.cb_args, dtt=dtt, **display_args)
  File "renpy/character.py", line 901, in do_display
    **display_args)
  File "renpy/character.py", line 647, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "renpy/ui.py", line 298, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "renpy/display/core.py", line 3315, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, **kwargs)
  File "renpy/display/core.py", line 3735, in interact_core
    root_widget.visit_all(lambda i : i.per_interact())
  File "renpy/display/core.py", line 568, in visit_all
    d.visit_all(callback, seen)
  File "renpy/display/core.py", line 568, in visit_all
    d.visit_all(callback, seen)
  File "renpy/display/core.py", line 568, in visit_all
    d.visit_all(callback, seen)
  File "renpy/display/core.py", line 568, in visit_all
    d.visit_all(callback, seen)
  File "renpy/display/core.py", line 568, in visit_all
    d.visit_all(callback, seen)
  File "renpy/display/core.py", line 568, in visit_all
    d.visit_all(callback, seen)
  File "renpy/display/core.py", line 568, in visit_all
    d.visit_all(callback, seen)
  File "renpy/display/core.py", line 570, in visit_all
    callback(self)
  File "renpy/display/core.py", line 3735, in <lambda>
    root_widget.visit_all(lambda i : i.per_interact())
  File "renpy/display/image.py", line 752, in per_interact
    self.find_target()
  File "renpy/display/image.py", line 652, in find_target
    raise Exception(error)
Exception: DynamicImage u'Create 1/Accessories/acc[Acc11].png': could not find image. (u'Create 1/Accessories/acc0.png')

While running game code:
  File "game/chapter2.rpy", line 520, in script
    Kevin "So you're back, how was the training today?"
Exception: DynamicImage u'Create 1/Accessories/acc[Acc11].png': could not find image. (u'Create 1/Accessories/acc0.png')
